// AUTO-GERADO a partir de apps/scraper/src/utils/skills_vocabulary.py
// Mantem sincronia manual: ao adicionar skill nova no Python, regenerar este arquivo.
// Comando (Bash): grep -oE '"[A-Z][^"]+"' apps/scraper/src/utils/skills_vocabulary.py | sort -u

export const SKILLS_VOCABULARY: ReadonlyArray<string> = [
  "A/B Testing","ABAC","ABAP","Active Directory","ActiveMQ",
  "Actix","Administrador de Banco de Dados","Administrador de Redes","Administrador de Sistemas","Adobe XD",
  "AdonisJS","Advanced Excel","Agile Coach","Agile","AI Engineer",
  "Aiohttp","Airflow","Alibaba Cloud","Allure","Alpine.js",
  "Amazon Web Services","Analista de Dados","Analista de Infraestrutura","Analista de QA","Analista de Seguranca",
  "Analista de Sistemas","Analista de Suporte","Analista de Testes","Analista DevOps","Analista Programador",
  "Android SDK","Android Studio","Android","Angular","AngularJS",
  "Anomaly Detection","Ansible","Ant Design","Anthropic","Apache Airflow",
  "Apache Beam","Apache Camel","Apache Druid","Apache Flink","Apache Hive",
  "Apache Hudi","Apache Iceberg","Apache Kafka","Apache NiFi","Apache Pinot",
  "Apache Pulsar","Apache Spark","Apache Storm","Apache Superset","Apache",
  "Apex","API Gateway","API","APIs","Apollo Server",
  "Apollo","AppDynamics","Appium","AppSec","ArangoDB",
  "Arduino","ArgoCD","Arquiteto de Software","Arquitetura Hexagonal","Arquitetura",
  "Aruba","Asana","ASP.NET Core","ASP.NET","ASR",
  "Assembly","AssertJ","Astro","AsyncAPI","ATDD",
  "Attention","Auth0","AutoGen","Automation Anywhere","AutoML",
  "Avro","AWS AppSync","AWS Athena","AWS Aurora","AWS Bedrock",
  "AWS CloudFormation","AWS CloudFront","AWS CloudWatch","AWS DMS","AWS EC2",
  "AWS ECS","AWS EKS","AWS EMR","AWS EventBridge","AWS Fargate",
  "AWS Glue","AWS IAM","AWS Kinesis","AWS KMS","AWS Lambda",
  "AWS RDS","AWS Redshift","AWS Route 53","AWS S3","AWS SageMaker",
  "AWS Secrets Manager","AWS SNS","AWS SQS","AWS Step Functions","AWS",
  "Azure Active Directory","Azure AD","Azure Boards","Azure Data Factory","Azure DevOps",
  "Azure Event Hub","Azure Functions","Azure ML","Azure OpenAI","Azure Pipelines",
  "Azure Repos","Azure Service Bus","Azure Synapse","Azure","Babel",
  "Babylon.js","Backbone","Backbone.js","Backend Developer","Backend for Frontend",
  "Backend","Back-End","Backup","Bacula","Bamboo",
  "Banco de Dados","Bash","Bazel","BCP","BDD",
  "Beam","Beats","Bedrock","BERT","BFF",
  "BGP","BI","BigCommerce","BIG-IP","BigQuery",
  "Bitbucket","Blender","Blue Prism","Blue Team","Boomi",
  "Bootstrap","BotCity","Bottle","BrowserStack","Btrfs",
  "Bugsnag","Buildah","Buildkite","Burp Suite","C#",
  "C++","Cacti","CAN bus","Capacitor","Capybara",
  "Carbon Black","Cargos EN","Cargos PT","Cassandra","CatBoost",
  "CCIE","CCNA","CCNP","CDK","CentOS",
  "Chai","Chakra UI","Chart.js","ChatGPT","Check Point",
  "Checkmarx","Chef","Chroma","CI/CD","Cibersseguranca",
  "Cientista de Dados","CIFS","CircleCI","Cisco","Citrix",
  "Claude","Clean Architecture","ClickHouse","ClickUp","Clojure",
  "Cloud Engineer","Cloud Functions","Cloud Native","Cloud Run","Cloud",
  "Cloudflare","CloudFormation","CNN","COBIT","COBOL",
  "Cocos2d","CodeIgniter","Colab","Colaboracao & Agile","Commvault",
  "Computer Vision","Concourse","Conda","Confluence","Consul",
  "Containerd","Cordova","Cosmos DB","Couchbase","CouchDB",
  "CQRS","CrewAI","Crossplane","CrowdStrike","Crystal",
  "CSS","CSS3","CTO","Cucumber","CV",
  "Cybersecurity","Cypress","D3","D3.js","Dagster",
  "Dapper","Dart","Dask","Data Analyst","Data Engineer",
  "Data Engineering","Data Lake","Data Pipeline","Data Science","Data Scientist",
  "Data Vault","Data Warehouse","Databricks","Datadog","Dataflow",
  "Dataproc","DB2","DBA","DCS","DDD",
  "Debian","Deep Learning","Delphi","Delta Lake","Desenvolvedor Back-End",
  "Desenvolvedor Front-End","Desenvolvedor Full Stack","Desenvolvedor Junior","Desenvolvedor Mobile","Desenvolvedor Pleno",
  "Desenvolvedor Senior","Desenvolvedor","Design Patterns","Detox","DevOps & SRE",
  "DevOps Engineer","DevOps","DevSecOps","DHCP","Diffusion Models",
  "DigitalOcean","DirectX","Disaster Recovery","Discord","Django",
  "DLP","DNS","Docker","Domain Driven Design","Domain-Driven Design",
  "Domo","Draw.io","Drogon","Drone CI","DRP",
  "Druid","Drupal","Dynamics 365","DynamoDB","Dynatrace",
  "EC2","Echo Framework","Echo","ECS","EDA",
  "Edge Computing","EDR","EIGRP","EKS","Elasticsearch",
  "Elixir","ELK Stack","ELK","ELT","Embedded & IoT",
  "Embedded Engineer","Embeddings","Ember","Ember.js","EMC",
  "Emotion","Engenheiro de Dados","Engenheiro de Software","Engenheiro de Testes","Engineering Manager",
  "English Fluent","Entity Framework","Entra ID","Envoy","Enzyme",
  "Epicor","Erlang","ERP & Corporativo","ESBuild","ESP32",
  "ESP8266","Espanhol Avancado","Espanhol Fluente","Espresso","Estagiario TI",
  "ESXi","ETL","Event Driven","Event Sourcing","Event-Driven",
  "Excel","Expo","Express","Express.js","Extreme Programming",
  "F#","F5","FaaS","FAISS","Falco",
  "FastAI","FastAPI","Fastify","FaunaDB","Fiber Go",
  "Fiber","Figma","Fine-tuning","Firebase","Firestore",
  "Firewall","Fivetran","Flask","Flink","Flow",
  "Flutter","Flux","Fly.io","FortiGate","Fortran",
  "FreeRTOS","Frontend Developer","Frontend","Front-End","Full Stack Developer",
  "Fullstack Developer","Fullstack","Full-Stack","Game & Graphics","Game Developer",
  "GameMaker","GAN","GANs","Gatling","Gatsby",
  "GCP","GDPR","Gemini","Gin Gonic","Gin",
  "Git","GitHub Actions","GitHub","GitLab CI","GitLab CI/CD",
  "GitLab","GitOps","Go Fiber","Go","Godot",
  "Golang","Google Cloud Platform","Google Cloud","Google Colab","Google Data Studio",
  "GPG","GPO","GPT","GPT-4","GPT-5",
  "Gradle","Grafana Tempo","Grafana","GraphQL","Groovy",
  "Group Policy","Hadoop","Hanami","Hapi","HAProxy",
  "HashiCorp Vault","HashiCorp","Haskell","Haystack","HBase",
  "HDFS","Head of Engineering","Helm","Help Desk","Helpdesk",
  "Heroku","Hexagonal Architecture","Hibernate","Highcharts","HIPAA",
  "Hive","HMI","Honeycomb","HSM","HSRP",
  "HTML","HTML5","Hudi","Hugging Face","HuggingFace",
  "Hyper-V","IAM","IBM Cloud","IBM DB2","IBM Storage",
  "Iceberg","Idiomas","IDS","Industria 4.0","Industry 4.0",
  "InfluxDB","Infor","Informatica","Information Security","Informix",
  "InfoSec","Ingles Avancado","Ingles Fluente","Ingles Intermediario","Insomnia",
  "Integromat","InVision","Ionic","IoT","IPS",
  "IPv4","IPv6","ISO 27001","Istio","ITIL",
  "Jaeger","JanusGraph","Jasmine","Java","JavaScript",
  "JAX","JD Edwards","JDBC","JDE","Jenkins",
  "Jest","Jetpack Compose","Jira","JMeter","Joomla",
  "JPA","JSON Schema","Julia","Junior Developer","Juniper",
  "JUnit","Jupyter","JupyterLab","JWT","K8s",
  "Kafka Connect","Kafka Streams","Kafka","Kanban","Karate DSL",
  "Karate","Keras","Keycloak","Kibana","KMM",
  "KMS","Koa","Kotlin Multiplatform","Kotlin","KPIs",
  "Kubeflow","Kubernetes","Kustomize","KVM","Lakehouse",
  "Lambda","LAN","LangChain","LangGraph","Laravel",
  "Lean","Less","LESS","LevelDB","LGPD",
  "LightGBM","Lightning","Linear","Linguagem R","Linguagens",
  "Linkerd","Linode","Linux","Lit","Llama",
  "LLaMA","LlamaIndex","LLM","LLMs","Load Balancer",
  "LoadRunner","Locust","Logstash","Loki","Looker Studio",
  "Looker","LoopBack","LoRA","LSTM","Lua",
  "Lucidchart","Luigi","Lumen","Machine Learning Engineer","Machine Learning",
  "Macros","Magento","Make","Make.com","MariaDB",
  "Material UI","Matillion","MATLAB","MAUI","Maven",
  "Maya","MCP","MediaPipe","Memcached","Mercurial",
  "Mermaid","MessagePack","Metabase","Metal","Metasploit",
  "MFA","Micronaut","Microservices","Microservicos","Microsoft Azure",
  "Microsoft Dynamics","Microsoft SQL Server","Microsoft Teams","Microsservicos","Microsserviços",
  "MicroStrategy","Mikrotik","Milvus","Mimir","Miro",
  "Mistral","ML & AI","ML Engineer","ML","MLflow",
  "MLOps Engineer","MLOps","Mobile Developer","Mobile","MobX",
  "Mocha","Modbus","Modin","Monday.com","MongoDB",
  "Monolithic","Monolito","Mosquitto","MPLS","MQTT",
  "MSSQL","MUI","MuleSoft","Mural","MXNet",
  "MySQL","Nagios","NAT","NativeScript","NATS",
  "Neo4j","Nessus","Nest.js","NestJS","NetApp",
  "Netlify","NetSuite","Network Engineer","New Relic","NewSQL",
  "Next.js","NextJS","Nexus","NFS","Nginx",
  "NiFi","Nightwatch","Nim","NIST","NLP",
  "NLU","Nmap","Node.js","NodeJS","Nomad",
  "NoSQL","Notion","NuGet","NumPy","Nuxt",
  "Nuxt.js","OAuth","OAuth2","ObjectBox","Objective-C",
  "OCaml","OCI","Octopus Deploy","OIDC","OKRs",
  "Okta","OLAP","OLTP","Onion Architecture","ONNX",
  "OPC UA","OpenAI","OpenAPI","OpenCV","OpenGL",
  "OpenID Connect","OpenSearch","OpenShift","OpenStack","OpenTelemetry",
  "Optuna","Oracle Cloud","Oracle Database","Oracle EBS","Oracle Fusion",
  "Oracle","OrientDB","OSPF","OTel","Outbox Pattern",
  "OWASP Top 10","OWASP ZAP","OWASP","Pact","Palo Alto",
  "Pandas","Parcel","Pascal","PCI DSS","Penetration Testing",
  "Pentaho","Pentest","Pentesting","PeopleSoft","Perforce",
  "Perl","PGP","Phaser","Phoenix","PHP",
  "Pinecone","Pinia","Pinot","Pipenv","PixiJS",
  "PKI","PL/SQL","PlanetScale","PlantUML","Platform Engineer",
  "Play Framework","Playwright","PLC","PMBOK","Podman",
  "Poetry","Polars","PostCSS","Postgres","PostgreSQL",
  "Postman","Power Automate","Power BI","PowerShell","Prefect",
  "Presto","PRINCE2","Principal Engineer","Product Manager","Product Owner",
  "Programador","Prometheus","Prompt Engineering","Protheus","Protobuf",
  "Protocol Buffers","Proxmox","PRTG","Pub/Sub","Pulsar",
  "Pulumi","Puppet","Puppeteer","Purple Team","PWA",
  "PySpark","Python","PyTorch","QA & Testing","QA Analyst",
  "QA Engineer","Qdrant","Qlik","QlikSense","QlikView",
  "QLoRA","QoS","Quarkus","QuestDB","Qwik",
  "R Programming","RabbitMQ","RAG","RAID","Rails",
  "Rancher","Raspberry Pi","Ray Tune","Ray","RBAC",
  "RDS","React Native","React Query","React Testing Library","React",
  "React.js","ReactJS","Realm","Recoil","Recommender Systems",
  "Red Team","Redash","RedHat","Redis","Redshift",
  "Redux Toolkit","Redux","Reinforcement Learning","Remix","Render",
  "REST API","REST Assured","REST","RESTful","RethinkDB",
  "RHEL","Riak","RLHF","RM TOTVS","RNN",
  "Robot Framework","Robotic Process Automation","Rocket","RocksDB","Rollbar",
  "Rollup","RPA & Automacao","RPA","RS-232","RS-485",
  "RSpec","RTOS","Ruby on Rails","Ruby","RUP",
  "Rust","RxJS","S/4HANA","S3","SAFe",
  "Saga Pattern","Sage","SageMaker","Sails","Salesforce",
  "SaltStack","SAML","Sanic","Sankhya","SAP ABAP",
  "SAP Ariba","SAP Basis","SAP BI","SAP BTP","SAP BW",
  "SAP CO","SAP Concur","SAP CPI","SAP CRM","SAP ECC",
  "SAP EWM","SAP FI","SAP Fiori","SAP HANA","SAP HCM",
  "SAP HR","SAP IBP","SAP MDG","SAP MM","SAP PM",
  "SAP PP","SAP PS","SAP QM","SAP S/4HANA","SAP SCM",
  "SAP SD","SAP Solution Manager","SAP SuccessFactors","SAP TM","SAP UI5",
  "SAP WM","SAP","SASS","Sauce Labs","SCADA",
  "Scala","Scikit-learn","Scrum Master","Scrum","Scrumban",
  "SCSS","ScyllaDB","SDET","SD-WAN","Security Analyst",
  "Security Engineer","Seguranca da Informacao","Seguranca","Selenium","Semantic Kernel",
  "Senior Developer","Senior Sistemas","Sentry","Serverless","Service Desk",
  "Service Mesh","ServiceNow","Shell Script","Shopify","SIEM",
  "Sinatra","Sinon","Sisense","Site Reliability Engineer","Site Reliability Engineering",
  "Six Sigma","Sketch","Slack","Slim","SMB",
  "Snowflake","SNS","Snyk","SOAP","SOAR",
  "SOC 2","SOC","Software Architect","Software Architecture","Software Developer",
  "Software Engineer","SOLID","Solid.js","Solidity","SolidJS",
  "Solr","Solutions Architect","SonarQube","Sophos","SOQL",
  "SOSL","Spanish Fluent","Spark","SpecFlow","Spinnaker",
  "Splunk","Spring Boot","Spring Cloud","Spring Security","Spring",
  "SQL Server","SQL","SQLAlchemy","SQLite","SQS",
  "SRE","SSAS","SSE","SSIS","SSL",
  "SSO","SSRS","Stable Diffusion","Staff Engineer","Star Schema",
  "Stimulus","Stitch","STM32","Storybook","STP",
  "Strapi","Styled Components","Stylus","Subversion","Supabase",
  "Superset","Suporte & Redes","Suporte de TI","Suporte Tecnico","Svelte",
  "SvelteKit","SVN","Swagger","Swift","SwiftUI",
  "SWR","Sybase","Symfony","Sysadmin","System Administrator",
  "System Design","T5","Tableau","Tailwind CSS","Tailwind",
  "Talend","TanStack Query","TCP/IP","TDD","TeamCity",
  "Tech Lead","Tech Recruiter","Technical Lead","Tecnico de Informatica","Tecnico de TI",
  "Tekton","TensorFlow","TensorRT","Terraform","Tesseract",
  "Test Automation","Test Engineer","Testing Library","TestNG","TestRail",
  "TFLite","Three.js","Thrift","Time Series","TimescaleDB",
  "TLS","Tornado","TOTVS","Traefik","Trainee",
  "Transformers","Travis CI","Trello","Trino","Triton Inference Server",
  "Trivy","T-SQL","TTS","Turbopack","Twelve Factor",
  "TypeScript","Ubuntu","UIKit","UiPath","Unity",
  "Unix","Unreal Engine","Unreal","Vapor","Vault",
  "VB.NET","VBA","Vector Database","Vector Search","Veeam",
  "Veracode","Vercel","Vert.x","Vertex AI","VirtualBox",
  "Visual Basic","Vite","Vitess","Vitest","VLAN",
  "VMware","VP of Engineering","VPN","VRRP","VTEX",
  "Vue","Vue.js","VueJS","Vulkan","W&B",
  "WAF","WAN","WASM","Waterfall","Weaviate",
  "Web Components","Web Developer","WebAssembly","WebdriverIO","WebGL",
  "Webpack","WebSocket","WebSockets","Weights & Biases","Whisper",
  "Windows Server","Wireshark","WooCommerce","WordPress","Workato",
  "Workday","WSDL","X.509","Xamarin","Xcode",
  "XCTest","XDR","Xen","XGBoost","XML",
  "XP","Xray","YAML","Yarn","Yii",
  "Zabbix","Zapier","ZBrush","Zephyr RTOS","Zephyr",
  "Zeplin","Zero Trust","ZeroMQ","ZFS","Zig",
  "Zipkin","Zoom","Zustand",
];

// Total: 1118 skills/papeis canonicos
